apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fasttechfoods-catalog-secrets
  namespace: fasttechfoods
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "e9c79217-2087-4d18-b4ad-bc2f241e3114"
    keyvaultName: "kv-fastechfood"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: SEC-BLOB-STORAGE-CONNECTION-STRING
          objectType: secret
          objectVersion: ""
        - |
          objectName: SEC-CONNECTION-STRING-PG-CATALOG-DATABASE
          objectType: secret
          objectVersion: ""
        - |
          objectName: SEC-JWT-SECRET
          objectType: secret
          objectVersion: ""
    tenantId: "1b4119a8-1ec6-4bec-98d9-4821b933e35b"
  secretObjects:
  - secretName: fasttechfoods-catalog-api-secrets
    type: Opaque
    data:
    - objectName: SEC-BLOB-STORAGE-CONNECTION-STRING
      key: BLOB_STORAGE_CONNECTION_STRING
    - objectName: SEC-CONNECTION-STRING-PG-CATALOG-DATABASE
      key: CONNECTION_STRING_DATABASE
    - objectName: SEC-JWT-SECRET
      key: JWT_SECRET
