apiVersion: apps/v1
kind: Deployment
metadata:
  name: fasttechfoods-catalog-api
  namespace: fasttechfoods
  labels:
    app: fasttechfoods-catalog-api
    component: api
    version: v1
    workflowFriendlyName: Build_and_deploy_an_app_to_AKS
    workflow: actions.github.com-k8s-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fasttechfoods-catalog-api
  template:
    metadata:
      labels:
        app: fasttechfoods-catalog-api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: fasttechfoods-auth-workload-identity-sa
      containers:
      - name: fasttechfoods-catalog-api
        image: fasttechfoods.azurecr.io/fasttechfoods-catalog-api:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - containerPort: 8081
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: fasttechfoods-catalog-api-secrets
              key: JWT_SECRET
        - name: CONNECTION_STRING_DATABASE
          valueFrom:
            secretKeyRef:
              name: fasttechfoods-catalog-api-secrets
              key: CONNECTION_STRING_DATABASE
        - name: BLOB_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: fasttechfoods-catalog-api-secrets
              key: BLOB_STORAGE_CONNECTION_STRING
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
          readOnly: true
        - name: tmp-volume
          mountPath: /tmp
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config-volume
        configMap:
          name: fasttechfoods-catalog-api-config
      - name: tmp-volume
        emptyDir: {}
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "fasttechfoods-catalog-secrets"
