apiVersion: v1
kind: Service
metadata:
  name: fasttechfoods-catalog-api-service
  namespace: fasttechfoods
  labels:
    app: fasttechfoods-catalog-api
    component: service-internal
    workflowFriendlyName: Build_and_deploy_an_app_to_AKS
    workflow: actions.github.com-k8s-deploy
spec:
  type: ClusterIP
  selector:
    app: fasttechfoods-catalog-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8081
    protocol: TCP