apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fasttechfoods-catalog-secrets
  namespace: fasttechfoods
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "kv-hackathon"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: SEC-BLOB-STORAGE-CONNECTION-STRING
          objectType: secret
          objectAlias: BLOB_STORAGE_CONNECTION_STRING
        - |
          objectName: SEC-CONNECTION-STRING-PG-CATALOG-DATABASE
          objectType: secret
          objectAlias: CONNECTION_STRING_DATABASE
        - |
          objectName: SEC-JWT-SECRET
          objectType: secret
          objectAlias: JWT_SECRET
    tenantId: "16b3c013-d300-468d-ac64-7eda0820b6d3"
  secretObjects:
  - secretName: fasttechfoods-catalog-api-secrets
    type: Opaque
    data:
    - objectName: BLOB_STORAGE_CONNECTION_STRING
      key: BLOB_STORAGE_CONNECTION_STRING
    - objectName: CONNECTION_STRING_DATABASE
      key: CONNECTION_STRING_DATABASE
    - objectName: JWT_SECRET
      key: JWT_SECRET
