name: Build and deploy ASP.Net Core app to Azure Web App - FastTechFoodsCatalog

on:
  push:
    branches:
      - disabled
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
       id-token: write #This is required for requesting the JWT
       contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/FastTechFoods.Api/FastTechFoods.Api.csproj

      - name: Build project
        run: dotnet build src/FastTechFoods.Api/FastTechFoods.Api.csproj --configuration Release --no-restore

      - name: Run unit tests
        # Altere para o projeto de testes correto se necessário
        run: dotnet test --no-build --configuration Release

      - name: Publish API
        run: dotnet publish src/FastTechFoods.Api/FastTechFoods.Api.csproj --configuration Release --output src/FastTechFoods.Api/publish --no-build

      - name: List publish folder contents
        run: ls -l src/FastTechFoods.Api/publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D4025572BB584FDB9D191654CD83E903 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7C376F2528184FBCBDCE727296B82725 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A50155B837614F2E982B12865A2C0A9B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FastTechFoodsCatalog'
          package: src/FastTechFoods.Api/publish
